import requests
import json
import xlsxwriter
r1 = requests.get('https://bugzilla.kernel.org/rest/login?login=jiawl28@uci.edu&password=ljw12345')
r1 = requests.get('https://bugzilla.kernel.org/rest/valid_login?login=jiawl28@uci.edu&token=209397-5fw5xknGJeOI9WchYhq6gp')
r1 = requests.get('https://bugzilla.kernel.org/rest/bug?token=209397-5fw5xknGJeOI9WchYhq6gp&format=json&status=RESOLVED&status=VERIFIED&status=REJECTED&status=CLOSED&status=DEFERRED&include_fields=last_change_time,creation_time,status,id,assigned_to')
#print(r1.status_code)
#print(r1.encoding)
print(r1.json())
print(type(r1.json()))
print(len(r1.json()['bugs']))
print(type(r1.json()['bugs']))
print(type(r1.json()['bugs'][0]))
print(r1.json()['bugs'][0])
result=[]
for bug in r1.json()['bugs']:
    data=[]
    data.append(bug['id'])
    data.append(bug['assigned_to_detail']['real_name'])
    data.append(bug['assigned_to_detail']['name'])
    data.append(bug['assigned_to_detail']['id'])
    data.append(bug['status'])
    data.append(bug['assigned_to'])
    data.append(bug['last_change_time'])
    data.append(bug['creation_time'])
    result.append(data)
workbook=xlsxwriter.Workbook('ClosedBugsInformation.xlsx')
worksheet=workbook.add_worksheet()
worksheet.set_column(0,0,10)
worksheet.set_column(1,2,20)
worksheet.set_column(3,3,10)
worksheet.set_column(5,5,25)
worksheet.set_column(6,7,20)
bold=workbook.add_format({'bold':True})
worksheet.write('A1','BugID',bold)
worksheet.write('B1','UserName',bold)
worksheet.write('C1','UserEmail',bold)
worksheet.write('D1','UserID',bold)
worksheet.write('E1','Status',bold)
worksheet.write('F1','AssignedTo',bold)
worksheet.write('G1','ClosedTime',bold)
worksheet.write('H1','CreationTime',bold)
row,col=1,0
for id,realname,name,uid,status,assignedto,lastchangetime,creationtime in result:
    worksheet.write(row,col,id)
    worksheet.write(row,col+1,realname)
    worksheet.write(row,col+2,name)
    worksheet.write(row,col+3,uid)
    worksheet.write(row,col+4,status)
    worksheet.write(row,col+5,assignedto)
    worksheet.write(row,col+6,lastchangetime)
    worksheet.write(row,col+7,creationtime)
    row+=1
workbook.close()